### ISSUE TITLE
NodeMCU / ESP8266 weird flashing

### ISSUE THREAD

**Issue by craigrobbo** [MickTheMechanic/Shiftlight#10]
Hi there.

I am still pretty new to coding and trying to learn, i tried the code on my NODEMCU, the initial start up animation seems to work fine (I have not  yet connected to my engine as I am awaiting my transistors) but every 5 seconds or so all the LEDs flash red for a very brief moment, on my Arduino UNO it doesn't do this.

I was hoping to migrate to the ESP platform as I have some custom PCB boards for an ESP8266 project which would suit this and keep the physical size package really small.

EDIT: Changing the colour of the "over rev protection" appears to change the colour of this flashing, so it seems to be attempting to display the over rev but only a single flash every 5 seconds, I did try changing the pins around in case this was an issue to no avail.

Thank you 

Craig

**Comment by Marius1418** [comment]
hello, 

I have the same issue with Pico board, did you manage to solve it?

**Comment by MickTheMechanic** [comment]
Is anything connected to the tacho signal input when this occurs? If not then its probably just noise being registered as frequency. Try gounding the tacho pin when bench testing.
