### ISSUE TITLE
Compatibility with OBD2 Standard (2005 Suzuki Swift)

### ISSUE THREAD

**Issue by ElectronicallyE** [MickTheMechanic/Shiftlight#19]
Hi @MickTheMechanic,

I'm trying to make your shift light project compatible with a 2005 Suzuki Swift EZ RS415 which support K-line communication known as [ISO 9141-2](https://www.suzuki-forums.com/threads/suzuki-swift-ecu-reading.277364/post-1622460) (ISO 14230-4 is backwards compatible).

Direct quote from the [Suzuki workshop service manual](https://www.allcarmanuals.com/factory-service-manual-233-Suzuki-Swift.html):
_**Data Link Connector (DLC)**
DLC (1) is in compliance with SAE J1962 in the shape of connector and pin assignment.
OBD serial data line (3) (K line of ISO 9141) is used for SUZUKI scan tool or OBD generic scan tool to communicate with ECM, Air bag SDM, immobilize control module (in ECM), BCM (Body electrical Control Module), TCM (Transmission Control Module) and ABS control module._

Looking at your [forum post](https://livetodai.com/t/arduino-rpm-light-shift-light/2545), you are using pin 9 for the RPM signal. I can't seem to find a OBD2 protocol that uses pin 9. Diagrams online state it is 'vendor option', 'manufacturer' or 'make/model specific'.

A few questions:
1. Could you please let me know the OBD2 standard used by your Daihatsu M100 (1998-2004) which the project is designed for?
2. Do you know if my car is compatible with your circuit diagram and code?

I have an oscilloscope to verify the signal type. If you would like me to verify, please let me know what I need to check.

Thanks,

Lachlan

**Comment by yu835730500** [comment]
Arduino board (can use Nano, Teensy, Pro Micro, Uno....)
OBD II connector 
CAN Bus MCP2515 module

**Comment by ElectronicallyE** [comment]
Thanks mate, much appreciated.
