### ISSUE TITLE
Trying to get the project running 

### ISSUE THREAD

**Issue by Lakshitha747** [MickTheMechanic/Shiftlight#4]
Mike,

Thanks for the project. Trying to get the code working for my honda (4 cylinder). Did everything according to your diagram without using the LM7805 as im powering my Arduino Uno from my laptop for now. This works but I'm getting frequency values when my ECU wire is not connected and the the idle frequency is showing in the high 40000. The -12v, is it fixed to the chasis as earth or?. If you could find the time to help me that would be really great. Im sort of new to this and I have no idea whats going on

Thank you

**Comment by MickTheMechanic** [comment]
Very strange indeed... the same problem was reported in #3 

I will need to look into this further. I know of several other people who have successfully built the project without issues, so I am fairly confident it’s not an issue with the code. 

Can you provide more information, like what you are using as a signal, does the bug also appear when you have the signal wire connected etc etc...

**Comment by Lakshitha747** [comment]
Thanks for your help,

Yeah its the same when its connected. It cant be an issue with the code cause the first time I tested it I got the proper values. The idle frequency was at 30Hz and when pin was removed it was showing 0Hz

**Comment by Lakshitha747** [comment]
Working on getting you the pictures. Actually didn't expect a reply so quickly

**Comment by MickTheMechanic** [comment]
I found the problem, my wiring diagram is wrong... I will post an updated version in a few moments

**Comment by Lakshitha747** [comment]
Thank you for the help.

**Comment by MickTheMechanic** [comment]
![43231FE9-B0A0-4185-BEA6-BA8ADE258A0D](https://user-images.githubusercontent.com/44751666/120033267-a6bc8000-bffb-11eb-93ac-1bffded019b0.jpeg)



please try this configuration with the PNP transistor and let me know how it works. 

Also make sure your Arduino gnd pin has a connection to the car body when you are powering via the laptop.

**Comment by Lakshitha747** [comment]
Alright thanks. I'll let you know how this goes

**Comment by MickTheMechanic** [comment]
Did it work out for you?

**Comment by Lakshitha747** [comment]
Sorry waiting on the transistors. Country is on lock down bit hard to get the stuff. I'll update the forum as soon as I get the parts and build the circuit. Is there another alternative to the transistor that you know of other than the PNP transistor #2N3906?

**Comment by MickTheMechanic** [comment]
Do you have any other PNP transistors?

**Comment by Lakshitha747** [comment]
s8550, s8050 transistor

**Comment by MickTheMechanic** [comment]
You can try the S8550, it would probably work.

**Comment by Lakshitha747** [comment]
Alright. I'll try with the S8550 and let you know

**Comment by MickTheMechanic** [comment]
Any luck?

**Comment by Lakshitha747** [comment]
Trying it right now with a S8050 transistor (cant seem to find my S8550 transistors). Trying to print igfreq but the serial monitor shows nothing. I have a random println in the loop and even that doesn't print. Can this be expected when running with this transistor?

**Comment by Lakshitha747** [comment]
Ok so now its printing a bunch of zeros
 
![Screenshot (15)](https://user-images.githubusercontent.com/32756759/120596274-2cf41e80-c461-11eb-838c-74f38fc5b797.png)

**Comment by Lakshitha747** [comment]
Yeah now I took the ground off and now its showing 50s 49s. When the revs increase it increases by like +1 not much and on idle and even when the vehicle is off its saying a constant 50. Looks like the transistor. I'll have get new ones

![Screenshot (16)](https://user-images.githubusercontent.com/32756759/120604185-68471b00-c46a-11eb-8cf5-bf2da5328f10.png)

**Comment by Lakshitha747** [comment]
Well my transistors finally came and I tried it with the 2N3906 and it works. Thanks for all your help with this. Just one more thing, when I do use this with the 12v, I can use a step down converter to reduce the voltage and power the Arduino and the rest of the circuitry will stay the same?

![ezgif com-gif-maker](https://user-images.githubusercontent.com/32756759/120893895-2c12e680-c633-11eb-8d8a-8d84080c832a.gif)

The frequencies are set pretty low

**Comment by MickTheMechanic** [comment]
Yes, you can use either a stepdown or a linear regular, and the rest will stay the same. 

Which wiring diagram worked for you in the end?

**Comment by Lakshitha747** [comment]
This one

 ![43231FE9-B0A0-4185-BEA6-BA8ADE258A0D](https://user-images.githubusercontent.com/44751666/120033267-a6bc8000-bffb-11eb-93ac-1bffded019b0.jpeg)

**Comment by Lakshitha747** [comment]
I'll close this issue now. Again thanks for your help with this.

**Comment by JeFeRoJo** [comment]
> Well my transistors finally came and I tried it with the 2N3906 and it works. Thanks for all your help with this. Just one more thing, when I do use this with the 12v, I can use a step down converter to reduce the voltage and power the Arduino and the rest of the circuitry will stay the same?
> 
> ![ezgif com-gif-maker](https://user-images.githubusercontent.com/32756759/120893895-2c12e680-c633-11eb-8d8a-8d84080c832a.gif)
> 
> The frequencies are set pretty low

Hello. 

I just created an account here to ask you how you have implemented the display with the RPM counter.
I am also trying to get the project to work on my Honda (EUDM Civic EK3) and am going to test it again with the new published diagram.

Thanks!
