### ISSUE TITLE
finding schematics

### ISSUE THREAD

**Issue by eddygor** [MickTheMechanic/Shiftlight#6]
Hi Mick. First off fantastic job, Thank you for posting this project. Your instructions are very clear even for a learner like myself. I am hoping to adapt this to work on my 1986 golf GTI. only issue I'm having is the note on the bottom of the schematic says  there is a mistake, and the correct schematic is in "issue 4". Where can I find issue 4 (or the correct schematic) as I am new to GitHub. many thanks eddy

hope I've posted this in the correct place

**Comment by MickTheMechanic** [comment]
#4
