### ISSUE TITLE
tachometer wire

### ISSUE THREAD

**Issue by GH-WRX** [MickTheMechanic/Shiftlight#8]
How are you sure it’s pin 9 on the obd2 connector?? every pin out i try and look at all says thier manufacturers, but i can’t find any information on what they are??

**Comment by MickTheMechanic** [comment]
Pin 9 on the obd is reserved for manufacturer specific use, which on Daihatsu happens to be the RPM signal.

**Comment by GH-WRX** [comment]
Are you able to help me find where the tacho is on a ford focus 2014 mk3? I cant find any information and the ford forums arnt any help; I know toyota also used 9 as rpm too

**Comment by MickTheMechanic** [comment]
You need to do some research, what kind of ignition system you have and where you can tap into an rpm signal

**Comment by baileyfpv** [comment]
Hey, found some diagrams, what do you think about the violet wire?
![image](https://user-images.githubusercontent.com/64811690/171572110-64423499-2191-48c0-94ea-c7fb5ff4732f.png)

**Comment by baileyfpv** [comment]
http://excesstext.com/tag/duratec/

there us this website too which has a full diagram of everything in the duratech engine but I cant seem to find the tacho? but that violet wire in the diagram above seems like it could work no? using the coils as the tacho signal for the less?

**Comment by MickTheMechanic** [comment]
No, the violet wire isn’t the Tacho signal. It’s possible the Tacho signal is transmitted on the can-bus. 

Do your coils have two wires or three?

**Comment by baileyfpv** [comment]
Unsure, Id say 2 since its a 2.0l ti-dcv

**Comment by baileyfpv** [comment]
Wait Its two since thats the diagram from my engine?

**Comment by MickTheMechanic** [comment]
Yeah, can’t help you if you’re unsure. I suggest you take a look, and find a full wiring diagram for the engine electrics that matches your car and post it here

**Comment by baileyfpv** [comment]
Surly you can take a quick look, I assure you its pretty hard, I don't see why its so secretive about wiring

**Comment by MickTheMechanic** [comment]
What’s your engine code?

**Comment by MickTheMechanic** [comment]
And how much power does the engine make? I need those things so I can find the correct wiring diagram

**Comment by baileyfpv** [comment]
2.0L 2000cc, duratec ti-vct 2014, 160hp engine code R9DA

**Comment by baileyfpv** [comment]
Scratch that its TXDB 120kw

**Comment by baileyfpv** [comment]
petrol

**Comment by MickTheMechanic** [comment]
Is it possible it’s the XTDB? 1.6l?? I can’t find the TXDB

**Comment by baileyfpv** [comment]
2.0L not exactly sure if it is but google says it’s should be the TXDB from
2014

**Comment by MickTheMechanic** [comment]
What do the registration papers say? It’s important we have the right wiring diagram..

**Comment by baileyfpv** [comment]
I’ll take a look tomorrow and let you know

**Comment by GH-WRX** [comment]
There is no information that I can find unless I’m looking wrong..
